name: Publish Docker Image

# Controls when the action will be run
# add schedule for action if needed
# schedule:
#     - cron: '37 1 * * 6'
on:
  # triggers on push or pull request events on main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # base container to build on
    runs-on: ubuntu-latest
    # sequence of tasks in the build process
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Docker Hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/cups
    
    - name: Setup buildx environment
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/arm/v7,linux/arm64,linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cups:latest
        labels: ${{ steps.meta.outputs.labels }}
    